pagination on purchase order listing and filter in invoice
cybergroupdevs/UniVerseDb pull request #60
Opened 2020-03-12 17:33 UTC by himanshu1365

2020-03-16 18:32 UTC, himanshu1365 commented
Conversion code used for ORDER.DATE field in PO.ORDER.MST is 'D-YMD[4,2,2]'

2020-03-18 16:46 UTC, vishivish18 requested changes
@himanshu1365  look in to the comments. Moreover I see that hast Lakshya did for invoices is very similar to what you have done for PO. Look how can we reduce the repetition of code and write common reusable functions, both on the front end and backend.

2020-03-18 16:46 UTC, vishivish18 commented on Frontend/tailored-brand-poc/src/app/invoice-detail/invoice-detail.component.ts
> +    this.purchaseOrderService.list(0,false)
start using named params from ES6, use destructuring it will help anyone understand the params

2020-03-18 16:46 UTC, vishivish18 commented on Frontend/tailored-brand-poc/src/app/purchase-order/all-purchase-orders/all-purchase-orders.component.html
> +          <th style="text-align: right;" scope="col" width="30%">Purchase Order No.</th>
make classes for these repetitive CSS

2020-03-18 16:46 UTC, vishivish18 commented on Frontend/tailored-brand-poc/src/app/purchase-order/all-purchase-orders/all-purchase-orders.component.html
> +            <td style="text-align: right;" class="align-right">{{rowId+i }}</td>
Same as above, make classes for these styles

2020-03-19 11:47 UTC, himanshu1365 commented on Frontend/tailored-brand-poc/src/app/purchase-order/all-purchase-orders/all-purchase-orders.component.html
> +          <th style="text-align: right;" scope="col" width="30%">Purchase Order No.</th>
Vishal I have corrected everything.

2020-03-20 13:28 UTC, vishivish18 commented on Frontend/tailored-brand-poc/src/app/invoice-detail/invoice-detail.component.ts
> +    this.purchaseOrderService.list(0,false)
@himanshu1365 ??

2020-03-20 13:29 UTC, vishivish18 approved these changes

2020-03-20 13:29 UTC, merged