All invoices pagination and filtering done
cybergroupdevs/UniVerseDb pull request #63
Opened 2020-03-17 12:18 UTC by lakshyakalia

2020-03-18 16:34 UTC, vishivish18 commented on Frontend/tailored-brand-poc/src/app/all-invoices/all-invoices.component.html
> +            <td>{{ rowId + i }}</td>
why 15% ?

2020-03-18 16:42 UTC, vishivish18 requested changes
@lakshyakalia  please look in to my comments and let me know

2020-03-18 16:42 UTC, vishivish18 commented on Frontend/tailored-brand-poc/src/app/all-invoices/all-invoices.component.html
> +            <td>{{ rowId + i }}</td>
why is width `15%` ?

2020-03-18 16:42 UTC, vishivish18 commented on Frontend/tailored-brand-poc/src/app/all-invoices/all-invoices.component.html
> +      [pageSizeOptions]="[5]"
make pageSizeOptions a variable as well.

2020-03-18 16:42 UTC, vishivish18 commented on Frontend/tailored-brand-poc/src/app/all-vendors/all-vendors.component.ts
> +  pageSize = 10
why do we have different Pagesizes?

2020-03-18 16:42 UTC, vishivish18 commented on Frontend/tailored-brand-poc/src/app/all-vendors/all-vendors.component.ts
> +  pagination(event){
what does this function do here?

2020-03-18 16:42 UTC, vishivish18 commented on Frontend/tailored-brand-poc/src/app/invoice-detail/invoice-detail.component.ts
> +                this.createNewFormControl(res.ids[i], res.quantity[i],0)
start using named params in functions, use ES6 restructuring. It will help any one understand what these params are.

2020-03-18 16:42 UTC, vishivish18 commented on Frontend/tailored-brand-poc/src/app/purchase-order/all-purchase-orders/all-purchase-orders.component.ts
> +  purchaseOrderForm = new FormGroup({
shouldn't these have validations?

2020-03-19 06:41 UTC, lakshyakalia commented on Frontend/tailored-brand-poc/src/app/all-invoices/all-invoices.component.html
> +      [pageSizeOptions]="[5]"
I should make it an array or define it in ts?

2020-03-19 06:42 UTC, lakshyakalia commented on Frontend/tailored-brand-poc/src/app/all-vendors/all-vendors.component.ts
> +  pageSize = 10
This has been changed in rawat's PR

2020-03-19 06:42 UTC, lakshyakalia commented on Frontend/tailored-brand-poc/src/app/all-vendors/all-vendors.component.ts
> +  pagination(event){
Changed in rawat's PR

2020-03-19 06:49 UTC, lakshyakalia commented on Frontend/tailored-brand-poc/src/app/all-invoices/all-invoices.component.html
> +            <td>{{ rowId + i }}</td>
If the width isn't 15% , the input gets cramped

2020-03-19 06:50 UTC, lakshyakalia commented on Frontend/tailored-brand-poc/src/app/invoice-detail/invoice-detail.component.ts
> +                this.createNewFormControl(res.ids[i], res.quantity[i],0)
Ok , i will do that.

2020-03-20 04:33 UTC, lakshyakalia commented on Frontend/tailored-brand-poc/src/app/purchase-order/all-purchase-orders/all-purchase-orders.component.ts
> +  purchaseOrderForm = new FormGroup({
They are filters , so they don't require validations

2020-03-20 13:30 UTC, vishivish18 approved these changes

2020-03-22 09:44 UTC, merged